### PR TITLE
Add CLIMB Acceptable Use Policy

### PR DESCRIPTION
**Pull request by michaelchapman**
Add CLIMB Acceptable Use Policy, data classification table and link from index.

### CODE REVIEW

**Comment by SamStudio8** [comment]
Hi @michaelchapman, can we separate the classification document from this PR? I'd like to approve the AUP but discuss other options for hosting the classification list.

**Comment by michaelchapman** [comment]
No problem, I've taken that and the link from the main policy out for now. We can add back once we've decided where to keep it.

**Comment by michaelchapman** [comment]
Hi @SamStudio8, any further thoughts on this one? It would be good to get it published and be able to start pointing people to the agreed rules.

**Comment by SamStudio8** [comment]
Approved by @nickloman - pulling now

**Pull request merged**
